# Site settings
title: Chad Bartels
header-img: "img/home-bg.jpg"
email: chad.bartels@gmail.com
description: "Full stack Rails and Javascript developer"
baseurl: ""
url: "chadbartels.com"
twitter_username: chadbartels
github_username:  chaddy81
facebook_username:  chadb81

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
