name = "chadbartels.com"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "A minimal Hugo theme for Chad Bartels' personal site."
homepage = "https://chadbartels.com"
tags = ["minimal", "blog", "personal"]
features = ["responsive", "blog"]
min_version = "0.41.0"

[author]
  name = "Chad Bartels"
  homepage = "https://chadbartels.com"
